FROM node:22.17.0-alpine AS base
WORKDIR /app

# Install dependencies
COPY . .
RUN corepack enable && pnpm install --frozen-lockfile --prod=false

# Run seed
CMD ["pnpm", "--filter", "@pagespace/db", "db:seed"]